version: '3'

services:
  mysql:
    image: mysql:8.0.30-debian
    container_name: mysql-nest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-nest
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
